version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    networks:
      - ecommerce-net
    volumes:
      - mysql-data:/var/lib/mysql

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    networks:
      - ecommerce-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "8082:8082"
    networks:
      - ecommerce-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass

networks:
  ecommerce-net:

volumes:
  mysql-data:
